### ISSUE TITLE
Issue with build cache

### ISSUE THREAD

**Issue by j-roskopf** [j-roskopf/ComposeGuard#42]
Also found a similar problem with the build cache, if you want, I can create a separate ticket for this:

              1. Run `./gradlew clean`
              2. Run `./gradlew :feature:debugComposeCompilerCheck --build-cache`
              3. Run `./gradlew clean`
              4. Run `./gradlew :feature:debugComposeCompilerCheck --build-cache`
              
              Check will fail with `compose_reports not exists` error

_Originally posted by @matejdro in https://github.com/j-roskopf/ComposeGuard/issues/41#issuecomment-2292851419_

**Comment by j-roskopf** [comment]
With the recent fixes from other reported issues, this issue is no longer occurring and is working as expected

**Comment by matejdro** [comment]
Thanks for looking into it!

As mentioned on the commit comment, I think `--rerun-tasks` workaround is way overkill as it will forcefully invalidate whole project, completely negating the up to date checks and build cache. For example:

1. Start with a clean build folder (but with all outputs ready in config cache)
2. Run `:feature:debugComposeCompilerCheck`
3. Compile output for everything is loaded from build cache
4. Final `debugComposeCompilerCheck` runs
5. It detects that `compose_reports` is missing (because that folder is not part of the build cache, since it's not marked as task output)
6. It forces rerun of everything
7. Whole point of build cache is negated

A better workaround would probably be adding `compose_reports` folder as an output to the kotlin compile task, but as mentioned in the other task, this comes with a risk of kotlin tasks invalidating each other, so each compile task should have a different output folder.

**Comment by j-roskopf** [comment]
Can you elaborate a bit more on each compile task having a different output folder? I'm following in theory, but not understanding how that translates to code. adding compose_reports folder as an output to the kotlin compile task makes sense to me, but each compile task having a different output folder doesn't. we are referring to another kotlin compile task like ksp right?

**Comment by j-roskopf** [comment]
I published a 2.2.4-alpha with the kotlin task having the output directory of the check task added. I understand the risk of the other compile tasks like ksp being invalidated, but that seems like a fair tradeoff for the time being

**Comment by matejdro** [comment]
Seems to be working. Thanks!
